# Generated by Django 4.1.2 on 2022-11-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author_id', 'object')},
        ),
    ]
