# Generated by Django 4.1.2 on 2022-10-29 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='content',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='itemType',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('follow', 'Follow'), ('like', 'Like'), ('misc', 'Misc')], default='misc', max_length=16),
        ),
        migrations.AddField(
            model_name='inbox',
            name='recieved',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 5, 13, 58, 56817)),
        ),
    ]
