# Generated by Django 4.1.2 on 2022-10-29 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_inbox_recieved_alter_like_objecturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='recieved',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 8, 9, 25, 285242, tzinfo=datetime.timezone.utc)),
        ),
    ]
