# Generated by Django 4.1.2 on 2022-10-30 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0007_like_refcomment_alter_inbox_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='recieved',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 5, 54, 50, 829827, tzinfo=datetime.timezone.utc)),
        ),
    ]
