# Generated by Django 4.1.2 on 2022-10-31 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0008_alter_inbox_recieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='content',
            new_name='item',
        ),
        migrations.AddField(
            model_name='like',
            name='objectType',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], default='post', max_length=16),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='recieved',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 22, 40, 22, 844920, tzinfo=datetime.timezone.utc)),
        ),
    ]
