# Generated by Django 4.1.2 on 2022-11-02 04:33

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_rename_content_inbox_item_like_objecttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Like',
            name='official_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
