# Generated by Django 4.1.2 on 2022-11-02 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_count'),
        ('likes', '0010_auto_20221101_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='objectType',
            new_name='object_type',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='refComment',
            new_name='ref_comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AddField(
            model_name='like',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='like',
            name='ref_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='recieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='objectURL',
            field=models.UUIDField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='official_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
