# Generated by Django 4.1.2 on 2022-11-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0011_rename_objecttype_like_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='context',
            field=models.CharField(default='no context', max_length=400),
        ),
        migrations.AlterField(
            model_name='like',
            name='objectURL',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='like',
            name='summary',
            field=models.CharField(default='no summary', max_length=400),
        ),
    ]
