# Generated by Django 4.1.2 on 2022-11-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0012_alter_like_context_alter_like_objecturl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
