# Generated by Django 4.1.2 on 2022-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0013_delete_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', editable=False, max_length=40),
        ),
    ]
