# Generated by Django 4.1.2 on 2022-11-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0014_like_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='type',
            new_name='_type',
        ),
    ]
