# Generated by Django 4.1.2 on 2022-11-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0015_rename_type_like__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='_type',
            new_name='type',
        ),
    ]
