# Generated by Django 4.1.2 on 2022-11-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'get_latest_by': 'id'},
        ),
    ]
