# Generated by Django 4.1.2 on 2022-11-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'get_latest_by': 'id'},
        ),
    ]
