# Generated by Django 4.1.2 on 2022-11-10 23:02

import authors.models.author
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='follow',
            name='actor',
            field=models.URLField(validators=[authors.models.author.validate_author_url]),
        ),
        migrations.AlterField(
            model_name='follow',
            name='target',
            field=models.URLField(validators=[authors.models.author.validate_author_url]),
        ),
    ]
