# Generated by Django 4.1.2 on 2022-11-12 08:29

import authors.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0004_follow_remote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='actor',
            field=models.URLField(max_length=1000, validators=[authors.util.AuthorUtil.validate_author_url]),
        ),
        migrations.AlterField(
            model_name='follow',
            name='remote_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='follow',
            name='target',
            field=models.URLField(max_length=1000, validators=[authors.util.AuthorUtil.validate_author_url]),
        ),
    ]
