# Generated by Django 4.1.2 on 2022-11-15 03:34

from django.db import migrations, models
import uuid


# from https://gist.github.com/smcoll/8bb867dc631433c01fd0

def fill_mymodel_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Follow = apps.get_model('follow', 'Follow')
    for obj in Follow.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('follow', '0005_alter_follow_actor_alter_follow_remote_url_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='follow',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_mymodel_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='follow',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
        migrations.RemoveField('Follow', 'id'),
        migrations.RenameField(
            model_name='follow',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False),
        ),
    ]
