# Generated by Django 4.1.2 on 2022-11-20 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0006_alter_follow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='remote_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
