# Generated by Django 4.1.2 on 2022-11-20 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0007_follow_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='actor_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='follow',
            name='target_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
