# Generated by Django 4.1.2 on 2022-11-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0008_follow_actor_id_follow_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='target_id',
        ),
    ]
