# Generated by Django 4.1.2 on 2022-11-24 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0009_remove_follow_actor_id_remove_follow_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='remote_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
