# Generated by Django 4.1.2 on 2022-11-02 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow', '0001_initial'),
        ('post', '0002_post_count'),
        ('likes', '0013_delete_inbox'),
        ('comment', '0002_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.UUIDField(default=0)),
                ('item', models.UUIDField(default=0)),
                ('official_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('follow', 'Follow'), ('like', 'Like'), ('undef', 'Undef')], default='undef', max_length=16)),
                ('ref_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('ref_follow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='follow.follow')),
                ('ref_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='likes.like')),
                ('ref_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
