# Generated by Django 4.0.1 on 2022-10-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.TextField(blank=True),
        ),
    ]
