# Generated by Django 4.1.2 on 2022-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('local_author', 'Local Author'), ('active_remote_node', 'Active Remote Node'), ('inactive_remote_node', 'Inactive Remote Node')], default='local_author', max_length=25),
        ),
    ]
