# Generated by Django 4.1.2 on 2022-11-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.TextField(blank=True),
        ),
    ]
