# Generated by Django 4.1.2 on 2022-11-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remotenode_author_node_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotenode',
            old_name='password',
            new_name='remote_password',
        ),
        migrations.RenameField(
            model_name='remotenode',
            old_name='username',
            new_name='remote_username',
        ),
    ]
