# Generated by Django 4.1.2 on 2022-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
