# Generated by Django 4.1.2 on 2022-12-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_post'),
    ]
    
    operations = [
        migrations.RemoveField(
        model_name='comment',
        name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.JSONField(),
        ),
    ]
